# Shared per-sleeve kill-switch helpers - sourced by deploy_vps_live.sh + verify_vps_live.sh
# so the sleeve->units mapping and the on/off predicate live in ONE place (no drift between
# deploy and verify). Toggles come from deploy/sleeves.env (+ host override that can only
# narrow an enabled repo sleeve to off). bash-3.2-safe (no associative arrays).
# See deploy/sleeves.env for semantics.

# Space-separated unit lists per strategy target producer. Canonical demo/paper
# account owners are intentionally not sleeve-toggled: enabled producers require
# them, and the owners exclusively reconcile and protect account positions.
# Continuous is split into demo and deterministic-paper target producers.
LONG_SLEEVE_UNITS="liquidity-migration-bybit-long-demo.service liquidity-migration-bybit-long-paper.service"
CONTINUOUS_SLEEVE_UNITS="liquidity-migration-bybit-continuous-demo.service"
CONTINUOUS_PAPER_SLEEVE_UNITS="liquidity-migration-bybit-continuous-paper.service"
# Timer the continuous sleeve owns (the daily rmom-gate refresh). It runs when either
# continuous demo or continuous paper is on, because both need residual_momentum.parquet.
CONTINUOUS_SLEEVE_TIMERS="liquidity-migration-continuous-rmom-refresh.timer"
# The BTC/ETH hedge is a target-only continuous-demo add-on; the account owner
# remains the only process allowed to submit its resulting venue orders.
CONTINUOUS_HEDGE_TIMERS="liquidity-migration-continuous-hedge.timer"
CONTINUOUS_HEDGE_SERVICES="liquidity-migration-continuous-hedge.service"

LM_HOST_SLEEVES_ENV="${LM_HOST_SLEEVES_ENV:-/etc/liquidity-migration/sleeves.env}"
LM_RESOLVED_SLEEVES_ENV="${LM_RESOLVED_SLEEVES_ENV:-/etc/liquidity-migration/sleeves.resolved.env}"
LM_SYSTEMD_UNIT_DIR="${LM_SYSTEMD_UNIT_DIR:-/etc/systemd/system}"
LM_RUNTIME_SYSTEMD_UNIT_DIR="${LM_RUNTIME_SYSTEMD_UNIT_DIR:-/run/systemd/system}"

# Load the toggles: committed defaults first, then an optional per-host override. The
# host override is intentionally a safety NARROWING layer: it may turn a repo-on
# sleeve off for one box, but it may not turn a repo-off sleeve back on. Resolves the
# repo dir from this file's location so it works regardless of the caller's CWD.
lm_load_sleeve_toggles() {
    _lm_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    unset LONG_SLEEVE CONTINUOUS_SLEEVE CONTINUOUS_PAPER_SLEEVE 2>/dev/null || true
    [ -f "$_lm_dir/sleeves.env" ] && . "$_lm_dir/sleeves.env"
    _lm_repo_long="${LONG_SLEEVE:-off}"
    _lm_repo_continuous="${CONTINUOUS_SLEEVE:-off}"
    _lm_repo_continuous_paper="${CONTINUOUS_PAPER_SLEEVE:-off}"
    [ -f "$LM_HOST_SLEEVES_ENV" ] && . "$LM_HOST_SLEEVES_ENV"
    if ! sleeve_on "$_lm_repo_long"; then LONG_SLEEVE=off; fi
    if ! sleeve_on "$_lm_repo_continuous"; then CONTINUOUS_SLEEVE=off; fi
    if ! sleeve_on "$_lm_repo_continuous_paper"; then CONTINUOUS_PAPER_SLEEVE=off; fi
    # Fallbacks if NEITHER file set a toggle (a stripped checkout): EVERY sleeve
    # fails safe to OFF (audit 2026-06-12 round 3 - LONG previously failed OPEN,
    # so an accidentally deleted/renamed sleeves.env would have enabled and
    # restarted the long demo target producer against the operator's LONG=off
    # intent). The committed deploy/sleeves.env is the real source of truth;
    # these are last-resort. A missing config disables everything; it can never
    # resurrect a sleeve.
    : "${LONG_SLEEVE:=off}"
    : "${CONTINUOUS_SLEEVE:=off}"
    : "${CONTINUOUS_PAPER_SLEEVE:=off}"
}

# sleeve_on <value> -> 0 (true) if the toggle means "run this sleeve".
# An EMPTY/unset value is OFF (fail-safe, round 3) - callers load toggles first.
sleeve_on() {
    case "${1:-off}" in
        on|ON|On|1|true|TRUE|yes|YES) return 0 ;;
        *) return 1 ;;
    esac
}

continuous_rmom_refresh_on() {
    sleeve_on "${CONTINUOUS_SLEEVE:-off}" || sleeve_on "${CONTINUOUS_PAPER_SLEEVE:-off}"
}

lm_write_resolved_sleeve_toggles() {
    _lr_dir="$(dirname "$LM_RESOLVED_SLEEVES_ENV")"
    mkdir -p "$_lr_dir"
    _lr_tmp="$(mktemp "$LM_RESOLVED_SLEEVES_ENV.tmp.XXXXXX")"
    {
        echo "# Generated by deploy/lib_sleeves.sh. Do not edit by hand."
        echo "# Host overrides may only turn repo-on sleeves off; repo-off is a hard ceiling."
        printf 'LONG_SLEEVE=%s\n' "${LONG_SLEEVE:-off}"
        printf 'CONTINUOUS_SLEEVE=%s\n' "${CONTINUOUS_SLEEVE:-off}"
        printf 'CONTINUOUS_PAPER_SLEEVE=%s\n' "${CONTINUOUS_PAPER_SLEEVE:-off}"
        if [ -n "${CONTINUOUS_HEDGE_TIMER:-}" ]; then
            printf 'CONTINUOUS_HEDGE_TIMER=%s\n' "$CONTINUOUS_HEDGE_TIMER"
        fi
    } > "$_lr_tmp"
    chmod 0644 "$_lr_tmp"
    mv "$_lr_tmp" "$LM_RESOLVED_SLEEVES_ENV"
}

lm_verify_resolved_sleeve_toggles() {
    [ -f "$LM_RESOLVED_SLEEVES_ENV" ] || {
        echo "verify failed: missing resolved sleeve env $LM_RESOLVED_SLEEVES_ENV" >&2
        return 1
    }
    grep -Fx "LONG_SLEEVE=${LONG_SLEEVE:-off}" "$LM_RESOLVED_SLEEVES_ENV" >/dev/null || {
        echo "verify failed: resolved LONG_SLEEVE does not match loaded toggle" >&2
        return 1
    }
    grep -Fx "CONTINUOUS_SLEEVE=${CONTINUOUS_SLEEVE:-off}" "$LM_RESOLVED_SLEEVES_ENV" >/dev/null || {
        echo "verify failed: resolved CONTINUOUS_SLEEVE does not match loaded toggle" >&2
        return 1
    }
    grep -Fx "CONTINUOUS_PAPER_SLEEVE=${CONTINUOUS_PAPER_SLEEVE:-off}" "$LM_RESOLVED_SLEEVES_ENV" >/dev/null || {
        echo "verify failed: resolved CONTINUOUS_PAPER_SLEEVE does not match loaded toggle" >&2
        return 1
    }
    if [ -n "${CONTINUOUS_HEDGE_TIMER:-}" ]; then
        grep -Fx "CONTINUOUS_HEDGE_TIMER=$CONTINUOUS_HEDGE_TIMER" "$LM_RESOLVED_SLEEVES_ENV" >/dev/null || {
            echo "verify failed: resolved CONTINUOUS_HEDGE_TIMER does not match computed hedge state" >&2
            return 1
        }
    fi
}

apply_timer_enable() {
    _ate_flag="$1"; shift
    if sleeve_on "$_ate_flag"; then
        for _ate_u in "$@"; do systemctl enable --now "$_ate_u"; done
    else
        echo "kill-switch: timer group OFF -> disable --now: $*" >&2
        for _ate_u in "$@"; do systemctl disable --now "$_ate_u" 2>/dev/null || true; done
    fi
}

verify_timer() {
    _vt_flag="$1"; shift
    if sleeve_on "$_vt_flag"; then
        for _vt_u in "$@"; do
            systemctl is-enabled --quiet "$_vt_u" || { echo "verify failed: $_vt_u timer not enabled" >&2; return 1; }
            systemctl is-active --quiet "$_vt_u" || { echo "verify failed: $_vt_u timer not active" >&2; return 1; }
        done
    else
        for _vt_u in "$@"; do
            if systemctl is-active --quiet "$_vt_u" 2>/dev/null; then
                echo "verify failed: $_vt_u timer is OFF in sleeves.env but still active" >&2; return 1
            fi
            if systemctl is-enabled --quiet "$_vt_u" 2>/dev/null; then
                echo "verify failed: $_vt_u timer is OFF in sleeves.env but still enabled" >&2; return 1
            fi
        done
    fi
}

apply_hedge_timer_enable() {
    _ahte_flag="$1"
    apply_timer_enable "$_ahte_flag" $CONTINUOUS_HEDGE_TIMERS
    if ! sleeve_on "$_ahte_flag"; then
        echo "kill-switch: hedge lifecycle OFF -> stop service: $CONTINUOUS_HEDGE_SERVICES" >&2
        for _ahte_u in $CONTINUOUS_HEDGE_SERVICES; do systemctl stop "$_ahte_u" 2>/dev/null || true; done
    fi
}

verify_hedge_timer_enable() {
    _vhte_flag="$1"
    verify_timer "$_vhte_flag" $CONTINUOUS_HEDGE_TIMERS
    if ! sleeve_on "$_vhte_flag"; then
        for _vhte_u in $CONTINUOUS_HEDGE_SERVICES; do
            if systemctl is-active --quiet "$_vhte_u" 2>/dev/null; then
                echo "verify failed: $_vhte_u service is OFF in sleeves.env but still active" >&2
                return 1
            fi
        done
    fi
}

lm_expected_systemd_units() {
    _lesu_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    for _lesu_path in "$_lesu_dir"/systemd/liquidity-migration-*.service "$_lesu_dir"/systemd/liquidity-migration-*.timer; do
        [ -e "$_lesu_path" ] && basename "$_lesu_path"
    done
}

lm_host_liqmig_units() {
    {
        systemctl list-unit-files 'liquidity-migration-*' --no-legend --no-pager 2>/dev/null || true
        systemctl list-units 'liquidity-migration-*' --all --no-legend --no-pager --plain 2>/dev/null || true
        for _lhlu_path in \
            "$LM_SYSTEMD_UNIT_DIR"/liquidity-migration-*.service \
            "$LM_SYSTEMD_UNIT_DIR"/liquidity-migration-*.timer \
            "$LM_RUNTIME_SYSTEMD_UNIT_DIR"/liquidity-migration-*.service \
            "$LM_RUNTIME_SYSTEMD_UNIT_DIR"/liquidity-migration-*.timer; do
            [ -e "$_lhlu_path" ] && basename "$_lhlu_path"
        done
        # A retired unit file may already be gone while an operator/runtime
        # drop-in survives. Surface its owning unit name so cleanup removes the
        # orphaned override too; expected current-unit drop-ins remain intact.
        for _lhlu_dropin in \
            "$LM_SYSTEMD_UNIT_DIR"/liquidity-migration-*.service.d \
            "$LM_SYSTEMD_UNIT_DIR"/liquidity-migration-*.timer.d \
            "$LM_RUNTIME_SYSTEMD_UNIT_DIR"/liquidity-migration-*.service.d \
            "$LM_RUNTIME_SYSTEMD_UNIT_DIR"/liquidity-migration-*.timer.d; do
            [ -d "$_lhlu_dropin" ] && basename "$_lhlu_dropin" .d
        done
        # Broken enablement symlinks can outlive both the unit file and
        # systemd's list-unit-files output. Inventory them explicitly so an old
        # wants/requires link cannot resurrect after a later file reappears.
        for _lhlu_root in "$LM_SYSTEMD_UNIT_DIR" "$LM_RUNTIME_SYSTEMD_UNIT_DIR"; do
            [ -d "$_lhlu_root" ] || continue
            find "$_lhlu_root" -type l \
                \( -name 'liquidity-migration-*.service' -o -name 'liquidity-migration-*.timer' \) \
                -print 2>/dev/null
        done | while IFS= read -r _lhlu_link; do basename "$_lhlu_link"; done
    } | awk '{for (i = 1; i <= NF; i++) if ($i ~ /^liquidity-migration-.*\.(service|timer)$/) {print $i; break}}' | sed '/^$/d' | sort -u
}

lm_cleanup_unknown_liqmig_units() {
    _lcu_expected=" $(lm_expected_systemd_units | tr '\n' ' ') "
    for _lcu_unit in $(lm_host_liqmig_units); do
        case "$_lcu_expected" in
            *" $_lcu_unit "*) continue ;;
        esac
        echo "cleanup: unknown liquidity-migration unit -> disable/remove $_lcu_unit" >&2
        systemctl disable --now "$_lcu_unit" 2>/dev/null || true
        for _lcu_root in "$LM_SYSTEMD_UNIT_DIR" "$LM_RUNTIME_SYSTEMD_UNIT_DIR"; do
            rm -f "$_lcu_root/$_lcu_unit"
            if [ -d "$_lcu_root" ]; then
                find "$_lcu_root" -type l -name "$_lcu_unit" -delete 2>/dev/null || true
            fi
            _lcu_dropin_dir="$_lcu_root/$_lcu_unit.d"
            if [ -d "$_lcu_dropin_dir" ]; then
                find "$_lcu_dropin_dir" -mindepth 1 -delete
                rmdir "$_lcu_dropin_dir" 2>/dev/null || true
            fi
        done
        systemctl reset-failed "$_lcu_unit" 2>/dev/null || true
    done
}

lm_verify_no_unknown_liqmig_units() {
    _lvnu_expected=" $(lm_expected_systemd_units | tr '\n' ' ') "
    for _lvnu_unit in $(lm_host_liqmig_units); do
        case "$_lvnu_expected" in
            *" $_lvnu_unit "*) continue ;;
        esac
        echo "verify failed: unknown liquidity-migration unit present: $_lvnu_unit" >&2
        return 1
    done
}

# Install exactly the checked-in unit manifest without enabling or starting any
# current service/timer. Unknown historical units are stopped and removed because
# allowing a retired order mutator to survive this phase would defeat the point of
# a single-owner cutover. This function deliberately does not read or create the
# account-execution-capture-enabled authorization marker.
lm_install_current_systemd_units() {
    _licsu_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    for _licsu_required in \
        liquidity-migration-account-execution.service \
        liquidity-migration-account-paper-execution.service; do
        if [ ! -f "$_licsu_dir/systemd/$_licsu_required" ]; then
            echo "install failed: required account owner unit is absent from manifest: $_licsu_required" >&2
            return 1
        fi
    done
    mkdir -p "$LM_SYSTEMD_UNIT_DIR"
    for _licsu_path in \
        "$_licsu_dir"/systemd/liquidity-migration-*.service \
        "$_licsu_dir"/systemd/liquidity-migration-*.timer; do
        [ -e "$_licsu_path" ] || continue
        cp "$_licsu_path" "$LM_SYSTEMD_UNIT_DIR/$(basename "$_licsu_path")"
    done

    # Remove the named emergency mute from the current continuous producer. It
    # suppressed stale-ledger spam before notification ownership moved to the
    # account owner; retaining it would also suppress legitimate runner errors.
    for _licsu_root in "$LM_SYSTEMD_UNIT_DIR" "$LM_RUNTIME_SYSTEMD_UNIT_DIR"; do
        _licsu_quiet_dir="$_licsu_root/liquidity-migration-bybit-continuous-demo.service.d"
        rm -f "$_licsu_quiet_dir/telegram-quiet.conf"
        rmdir "$_licsu_quiet_dir" 2>/dev/null || true
    done

    systemctl daemon-reload
    lm_cleanup_unknown_liqmig_units
    systemctl daemon-reload
    lm_verify_no_unknown_liqmig_units
}

# apply_sleeve_enable <flag-value> <unit...> - on: `systemctl enable` each unit; off:
# `systemctl disable --now` each (stops it + survives the deploy). Default on => identical
# to the previous unconditional enables.
apply_sleeve_enable() {
    _ase_flag="$1"; shift
    if sleeve_on "$_ase_flag"; then
        for _ase_u in "$@"; do systemctl enable "$_ase_u"; done
    else
        echo "kill-switch: sleeve OFF -> disable --now: $*" >&2
        for _ase_u in "$@"; do systemctl disable --now "$_ase_u" 2>/dev/null || true; done
    fi
}

# verify_sleeve <flag-value> <unit...> - on: each unit must be active AND enabled; off: each
# unit must NOT be active (the kill-switch actually stopped it). Returns 1 (fail-loud) on mismatch.
verify_sleeve() {
    _vs_flag="$1"; shift
    if sleeve_on "$_vs_flag"; then
        for _vs_u in "$@"; do
            systemctl is-active --quiet "$_vs_u" || { echo "verify failed: $_vs_u not active" >&2; return 1; }
            systemctl is-enabled --quiet "$_vs_u" || { echo "verify failed: $_vs_u not enabled" >&2; return 1; }
        done
    else
        for _vs_u in "$@"; do
            if systemctl is-active --quiet "$_vs_u" 2>/dev/null; then
                echo "verify failed: $_vs_u is OFF in sleeves.env but still active" >&2; return 1
            fi
            if systemctl is-enabled --quiet "$_vs_u" 2>/dev/null; then
                echo "verify failed: $_vs_u is OFF in sleeves.env but still enabled" >&2; return 1
            fi
        done
    fi
}
