# The fleet's realm facts, looked up in deploy/realm_fields.tsv. That file is
# generated by liquidity_migration/policy/realms.py from deploy/realms.tsv,
# which is where a realm is declared and every name is derived; nothing here
# derives anything. Sourced by deploy/lib_sleeves.sh, and shipped verbatim to
# the VPS by scripts/deploy_vps_live.sh so the remote body reads realm facts
# before its checkout exists. LM_REALM_FIELDS_TEXT carries the file itself in
# that case.
#
# Every awk here reads its input to the end. The rows arrive through a pipe
# under `set -o pipefail`; a reader that exits on its first match closes that
# pipe while the writer is still writing, the writer dies of SIGPIPE, and the
# lookup answers 141 with the right value on stdout.
# shellcheck shell=bash

LM_REALM_FIELDS="${LM_REALM_FIELDS:-deploy/realm_fields.tsv}"

# ------------------------------------------------------------- realm facts

# The generated file's data rows. LM_REALM_FIELDS_TEXT wins over the file so a
# remote body can carry the facts before its checkout exists.
_lm_realm_field_rows() {
    if [ -z "${LM_REALM_FIELDS_TEXT:-}" ] && [ ! -f "$LM_REALM_FIELDS" ]; then
        echo "realm fields are missing: $LM_REALM_FIELDS" >&2
        return 1
    fi
    if [ -n "${LM_REALM_FIELDS_TEXT:-}" ]; then
        printf '%s\n' "$LM_REALM_FIELDS_TEXT"
    else
        cat "$LM_REALM_FIELDS"
    fi | LC_ALL=C awk '
NR == 1 && $0 != "# realm-fields-v1" { unsupported = 1 }
!unsupported && !/^#/ && !/^[[:space:]]*$/ { print }
END {
    if (unsupported) {
        print "realm fields have an unsupported schema; expected # realm-fields-v1" > "/dev/stderr"
        exit 1
    }
}
'
}

lm_realms() {
    _lm_realm_field_rows | LC_ALL=C awk -F '|' '!seen[$1]++ { print $1 }'
}

lm_funded_realms() {
    _lm_realm_field_rows | LC_ALL=C awk -F '|' '$2 == "kind" && $3 == "funded" { print $1 }'
}

# The one realm on a practice account: what the deploy soaks on.
lm_practice_realm() {
    _lm_realm_field_rows | LC_ALL=C awk -F '|' '$2 == "kind" && $3 == "practice" { print $1 }'
}

# `demo|mainnet|...` for the awk and case patterns below, in table order.
lm_realm_alternation() { lm_realms | paste -sd '|' -; }
lm_funded_alternation() { lm_funded_realms | paste -sd '|' -; }

lm_is_realm() {
    _lir_realm="$1"
    lm_realms | LC_ALL=C awk -v realm="$_lir_realm" '$0 == realm { found = 1 } END { exit found ? 0 : 1 }'
}

# One realm's declared column or derived name.
lm_realm_field() {
    _lrf_realm="$1"
    _lrf_field="$2"
    _lm_realm_field_rows | LC_ALL=C awk -F '|' \
        -v want_realm="$_lrf_realm" -v want_field="$_lrf_field" '
$1 == want_realm {
    realm_seen = 1
    if ($2 == want_field && !answered) { value = $3; answered = 1 }
}
END {
    if (answered) { print value; exit 0 }
    if (!realm_seen) {
        print "unknown realm: " want_realm > "/dev/stderr"
        exit 2
    }
    print "unknown realm field: " want_field > "/dev/stderr"
    exit 3
}
'
}
