# Shared per-sleeve kill-switch helpers - sourced by deploy_vps_live.sh + verify_vps_live.sh
# so the sleeve->units mapping and the on/off predicate live in ONE place (no drift between
# deploy and verify). Toggles come from deploy/sleeves.env (+ host override that can only
# narrow an enabled repo sleeve to off). bash-3.2-safe (no associative arrays).
# See deploy/sleeves.env for semantics.

# Space-separated unit lists per sleeve (entry/exit daemons + paper shadow). The risk service
# is intentionally NOT here - it always runs and protects every sleeve's open positions.
# The daily SHORT sleeve was ERASED from the system (operator order 2026-06-11);
# its units are gone and the deploy actively removes them from a live host. The
# old continuous-vs-daily report was later removed too; keep its orphaned unit
# files in this cleanup list so stale VPS timers do not keep failing daily.
# Continuous is split: the DEMO order-submitting sleeve vs the no-order PAPER
# evidence collector.
RETIRED_SLEEVE_UNITS="liquidity-migration-bybit-demo.service liquidity-migration-bybit-paper.service liquidity-migration-continuous-forward-report.service liquidity-migration-continuous-forward-report.timer"
LONG_SLEEVE_UNITS="liquidity-migration-bybit-long-demo.service liquidity-migration-bybit-long-paper.service"
CONTINUOUS_SLEEVE_UNITS="liquidity-migration-bybit-continuous-demo.service"
CONTINUOUS_PAPER_SLEEVE_UNITS="liquidity-migration-bybit-continuous-paper.service"
# Timer the continuous sleeve owns (the daily rmom-gate refresh). It runs when either
# continuous demo or continuous paper is on, because both need residual_momentum.parquet.
CONTINUOUS_SLEEVE_TIMERS="liquidity-migration-continuous-rmom-refresh.timer"
# The BTC-beta hedge is an order-submitting continuous-demo addon, not paper evidence.
CONTINUOUS_HEDGE_TIMERS="liquidity-migration-continuous-hedge.timer"
CONTINUOUS_HEDGE_SERVICES="liquidity-migration-continuous-hedge.service"

LM_HOST_SLEEVES_ENV="${LM_HOST_SLEEVES_ENV:-/etc/liquidity-migration/sleeves.env}"
LM_RESOLVED_SLEEVES_ENV="${LM_RESOLVED_SLEEVES_ENV:-/etc/liquidity-migration/sleeves.resolved.env}"

# Load the toggles: committed defaults first, then an optional per-host override. The
# host override is intentionally a safety NARROWING layer: it may turn a repo-on
# sleeve off for one box, but it may not turn a repo-off sleeve back on. Resolves the
# repo dir from this file's location so it works regardless of the caller's CWD.
lm_load_sleeve_toggles() {
    _lm_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    unset LONG_SLEEVE CONTINUOUS_SLEEVE CONTINUOUS_PAPER_SLEEVE 2>/dev/null || true
    [ -f "$_lm_dir/sleeves.env" ] && . "$_lm_dir/sleeves.env"
    _lm_repo_long="${LONG_SLEEVE:-off}"
    _lm_repo_continuous="${CONTINUOUS_SLEEVE:-off}"
    _lm_repo_continuous_paper="${CONTINUOUS_PAPER_SLEEVE:-off}"
    [ -f "$LM_HOST_SLEEVES_ENV" ] && . "$LM_HOST_SLEEVES_ENV"
    if ! sleeve_on "$_lm_repo_long"; then LONG_SLEEVE=off; fi
    if ! sleeve_on "$_lm_repo_continuous"; then CONTINUOUS_SLEEVE=off; fi
    if ! sleeve_on "$_lm_repo_continuous_paper"; then CONTINUOUS_PAPER_SLEEVE=off; fi
    # Fallbacks if NEITHER file set a toggle (a stripped checkout): EVERY sleeve
    # fails safe to OFF (audit 2026-06-12 round 3 - LONG previously failed OPEN,
    # so an accidentally deleted/renamed sleeves.env would have enabled and
    # restarted the order-submitting long demo against the operator's LONG=off
    # intent). The committed deploy/sleeves.env is the real source of truth;
    # these are last-resort. A missing config disables everything; it can never
    # resurrect a sleeve.
    : "${LONG_SLEEVE:=off}"
    : "${CONTINUOUS_SLEEVE:=off}"
    : "${CONTINUOUS_PAPER_SLEEVE:=off}"
}

# sleeve_on <value> -> 0 (true) if the toggle means "run this sleeve".
# An EMPTY/unset value is OFF (fail-safe, round 3) - callers load toggles first.
sleeve_on() {
    case "${1:-off}" in
        on|ON|On|1|true|TRUE|yes|YES) return 0 ;;
        *) return 1 ;;
    esac
}

continuous_rmom_refresh_on() {
    sleeve_on "${CONTINUOUS_SLEEVE:-off}" || sleeve_on "${CONTINUOUS_PAPER_SLEEVE:-off}"
}

lm_write_resolved_sleeve_toggles() {
    _lr_dir="$(dirname "$LM_RESOLVED_SLEEVES_ENV")"
    mkdir -p "$_lr_dir"
    _lr_tmp="$(mktemp "$LM_RESOLVED_SLEEVES_ENV.tmp.XXXXXX")"
    {
        echo "# Generated by deploy/lib_sleeves.sh. Do not edit by hand."
        echo "# Host overrides may only turn repo-on sleeves off; repo-off is a hard ceiling."
        printf 'LONG_SLEEVE=%s\n' "${LONG_SLEEVE:-off}"
        printf 'CONTINUOUS_SLEEVE=%s\n' "${CONTINUOUS_SLEEVE:-off}"
        printf 'CONTINUOUS_PAPER_SLEEVE=%s\n' "${CONTINUOUS_PAPER_SLEEVE:-off}"
        if [ -n "${CONTINUOUS_HEDGE_TIMER:-}" ]; then
            printf 'CONTINUOUS_HEDGE_TIMER=%s\n' "$CONTINUOUS_HEDGE_TIMER"
        fi
    } > "$_lr_tmp"
    chmod 0644 "$_lr_tmp"
    mv "$_lr_tmp" "$LM_RESOLVED_SLEEVES_ENV"
}

lm_verify_resolved_sleeve_toggles() {
    [ -f "$LM_RESOLVED_SLEEVES_ENV" ] || {
        echo "verify failed: missing resolved sleeve env $LM_RESOLVED_SLEEVES_ENV" >&2
        return 1
    }
    grep -Fx "LONG_SLEEVE=${LONG_SLEEVE:-off}" "$LM_RESOLVED_SLEEVES_ENV" >/dev/null || {
        echo "verify failed: resolved LONG_SLEEVE does not match loaded toggle" >&2
        return 1
    }
    grep -Fx "CONTINUOUS_SLEEVE=${CONTINUOUS_SLEEVE:-off}" "$LM_RESOLVED_SLEEVES_ENV" >/dev/null || {
        echo "verify failed: resolved CONTINUOUS_SLEEVE does not match loaded toggle" >&2
        return 1
    }
    grep -Fx "CONTINUOUS_PAPER_SLEEVE=${CONTINUOUS_PAPER_SLEEVE:-off}" "$LM_RESOLVED_SLEEVES_ENV" >/dev/null || {
        echo "verify failed: resolved CONTINUOUS_PAPER_SLEEVE does not match loaded toggle" >&2
        return 1
    }
    if [ -n "${CONTINUOUS_HEDGE_TIMER:-}" ]; then
        grep -Fx "CONTINUOUS_HEDGE_TIMER=$CONTINUOUS_HEDGE_TIMER" "$LM_RESOLVED_SLEEVES_ENV" >/dev/null || {
            echo "verify failed: resolved CONTINUOUS_HEDGE_TIMER does not match computed hedge state" >&2
            return 1
        }
    fi
}

apply_timer_enable() {
    _ate_flag="$1"; shift
    if sleeve_on "$_ate_flag"; then
        for _ate_u in "$@"; do systemctl enable --now "$_ate_u"; done
    else
        echo "kill-switch: timer group OFF -> disable --now: $*" >&2
        for _ate_u in "$@"; do systemctl disable --now "$_ate_u" 2>/dev/null || true; done
    fi
}

verify_timer() {
    _vt_flag="$1"; shift
    if sleeve_on "$_vt_flag"; then
        for _vt_u in "$@"; do
            systemctl is-enabled --quiet "$_vt_u" || { echo "verify failed: $_vt_u timer not enabled" >&2; return 1; }
            systemctl is-active --quiet "$_vt_u" || { echo "verify failed: $_vt_u timer not active" >&2; return 1; }
        done
    else
        for _vt_u in "$@"; do
            if systemctl is-active --quiet "$_vt_u" 2>/dev/null; then
                echo "verify failed: $_vt_u timer is OFF in sleeves.env but still active" >&2; return 1
            fi
            if systemctl is-enabled --quiet "$_vt_u" 2>/dev/null; then
                echo "verify failed: $_vt_u timer is OFF in sleeves.env but still enabled" >&2; return 1
            fi
        done
    fi
}

apply_hedge_timer_enable() {
    _ahte_flag="$1"
    apply_timer_enable "$_ahte_flag" $CONTINUOUS_HEDGE_TIMERS
    if ! sleeve_on "$_ahte_flag"; then
        echo "kill-switch: hedge lifecycle OFF -> stop service: $CONTINUOUS_HEDGE_SERVICES" >&2
        for _ahte_u in $CONTINUOUS_HEDGE_SERVICES; do systemctl stop "$_ahte_u" 2>/dev/null || true; done
    fi
}

verify_hedge_timer_enable() {
    _vhte_flag="$1"
    verify_timer "$_vhte_flag" $CONTINUOUS_HEDGE_TIMERS
    if ! sleeve_on "$_vhte_flag"; then
        for _vhte_u in $CONTINUOUS_HEDGE_SERVICES; do
            if systemctl is-active --quiet "$_vhte_u" 2>/dev/null; then
                echo "verify failed: $_vhte_u service is OFF in sleeves.env but still active" >&2
                return 1
            fi
        done
    fi
}

lm_expected_systemd_units() {
    _lesu_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    for _lesu_path in "$_lesu_dir"/systemd/liquidity-migration-*.service "$_lesu_dir"/systemd/liquidity-migration-*.timer; do
        [ -e "$_lesu_path" ] && basename "$_lesu_path"
    done
}

lm_host_liqmig_units() {
    {
        systemctl list-unit-files 'liquidity-migration-*' --no-legend --no-pager 2>/dev/null || true
        systemctl list-units 'liquidity-migration-*' --all --no-legend --no-pager --plain 2>/dev/null || true
        for _lhlu_path in /etc/systemd/system/liquidity-migration-*; do
            [ -e "$_lhlu_path" ] && basename "$_lhlu_path"
        done
    } | awk '{for (i = 1; i <= NF; i++) if ($i ~ /^liquidity-migration-/) {print $i; break}}' | sed '/^$/d' | sort -u
}

lm_cleanup_unknown_liqmig_units() {
    _lcu_expected=" $(lm_expected_systemd_units | tr '\n' ' ') "
    for _lcu_unit in $(lm_host_liqmig_units); do
        case "$_lcu_expected" in
            *" $_lcu_unit "*) continue ;;
        esac
        echo "cleanup: unknown liquidity-migration unit -> disable/remove $_lcu_unit" >&2
        systemctl disable --now "$_lcu_unit" 2>/dev/null || true
        rm -f "/etc/systemd/system/$_lcu_unit"
        systemctl reset-failed "$_lcu_unit" 2>/dev/null || true
    done
}

lm_verify_no_unknown_liqmig_units() {
    _lvnu_expected=" $(lm_expected_systemd_units | tr '\n' ' ') "
    for _lvnu_unit in $(lm_host_liqmig_units); do
        case "$_lvnu_expected" in
            *" $_lvnu_unit "*) continue ;;
        esac
        echo "verify failed: unknown liquidity-migration unit present: $_lvnu_unit" >&2
        return 1
    done
}

# apply_sleeve_enable <flag-value> <unit...> - on: `systemctl enable` each unit; off:
# `systemctl disable --now` each (stops it + survives the deploy). Default on => identical
# to the previous unconditional enables.
apply_sleeve_enable() {
    _ase_flag="$1"; shift
    if sleeve_on "$_ase_flag"; then
        for _ase_u in "$@"; do systemctl enable "$_ase_u"; done
    else
        echo "kill-switch: sleeve OFF -> disable --now: $*" >&2
        for _ase_u in "$@"; do systemctl disable --now "$_ase_u" 2>/dev/null || true; done
    fi
}

# verify_sleeve <flag-value> <unit...> - on: each unit must be active AND enabled; off: each
# unit must NOT be active (the kill-switch actually stopped it). Returns 1 (fail-loud) on mismatch.
verify_sleeve() {
    _vs_flag="$1"; shift
    if sleeve_on "$_vs_flag"; then
        for _vs_u in "$@"; do
            systemctl is-active --quiet "$_vs_u" || { echo "verify failed: $_vs_u not active" >&2; return 1; }
            systemctl is-enabled --quiet "$_vs_u" || { echo "verify failed: $_vs_u not enabled" >&2; return 1; }
        done
    else
        for _vs_u in "$@"; do
            if systemctl is-active --quiet "$_vs_u" 2>/dev/null; then
                echo "verify failed: $_vs_u is OFF in sleeves.env but still active" >&2; return 1
            fi
            if systemctl is-enabled --quiet "$_vs_u" 2>/dev/null; then
                echo "verify failed: $_vs_u is OFF in sleeves.env but still enabled" >&2; return 1
            fi
        done
    fi
}
