#!/usr/bin/env bash
# One thin operator-facing router for the surviving demo/paper and research operations.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SSH_TARGET="${SSH_TARGET:-root@116.202.15.128}"
REPO_DIR="${REPO_DIR:-/opt/liquidity-migration}"

if [[ -n "${PYTHON:-}" ]]; then
  PYTHON_BIN="$PYTHON"
elif [[ -x "$ROOT_DIR/.venv/bin/python" ]]; then
  PYTHON_BIN="$ROOT_DIR/.venv/bin/python"
elif [[ -x "$ROOT_DIR/.venv/Scripts/python.exe" ]]; then
  PYTHON_BIN="$ROOT_DIR/.venv/Scripts/python.exe"
else
  PYTHON_BIN="python3"
fi

# The canonical VPS scripts consume these environment variables.
export SSH_TARGET REPO_DIR

usage() {
  cat <<'EOF'
Usage: scripts/ops.sh <command> [arguments]

Safe operator commands:
  status [ARGS...]             read-only VPS verification
  equity [ARGS...]             standard descriptive equity curves
  research-refresh [ARGS...]   append-first data/features/backtest workflow
  reset [ARGS...]              remote ledger-reset preview (dry-run by default)
  venue-accounting [ARGS...]   capture/reconcile read-only demo accounting evidence
  wedged-command [ARGS...]     report/probe wedged order commands (read-only)
  wedged-command --execute resolve [ARGS...]
                               terminalize one wedged command on venue evidence
  real-money preflight         report every remaining arming step (read-only)
  real-money render-profile [--execute --output PATH]
                               render the operational profile from the
                               RM_* dials in the owner's env file
  test [PYTEST_ARGS...]        run pytest
  deploy --execute MODE        run install, activation, or guarded rollout
  help                         show this help and do nothing else

Environment overrides:
  SSH_TARGET   VPS SSH destination (default: root@116.202.15.128)
  REPO_DIR     repository path on the VPS (default: /opt/liquidity-migration)
  PYTHON       Python executable/path for local tools and tests

Safety contract:
  * This interface never enables REAL_MONEY or mainnet trading. real-money
    preflight only reports what is missing and never prints a secret;
    render-profile writes one non-secret profile artifact and nothing else.
  * reset is a remote dry-run unless --execute reaches the guarded reset script.
  * deploy requires --execute and MODE=install|activate|rollout.
  * Research runs remain research artifacts and are never auto-promoted.

Details: docs/operations.md
EOF
}

die_usage() {
  echo "ERROR: $*" >&2
  echo >&2
  usage >&2
  exit 2
}

remote_reset() {
  local -a reset_args=("$@")
  local arg has_execute=0 has_dry_run=0
  for arg in "${reset_args[@]:-}"; do
    if [[ "$arg" == "--execute" ]]; then
      has_execute=1
    elif [[ "$arg" == "--dry-run" ]]; then
      has_dry_run=1
    fi
  done

  # Make the safe default explicit at the remote boundary. The canonical reset
  # script independently defaults to dry-run and requires --execute as well.
  if (( has_execute == 0 && has_dry_run == 0 )); then
    reset_args=(--dry-run ${reset_args[@]+"${reset_args[@]}"})
  fi

  # Serialize values as Bash literals, then reconstruct a remote array. This
  # preserves argument boundaries (including spaces/metacharacters) without
  # eval. The only parsed source is generated by Bash's own printf %q.
  {
    printf 'REPO_DIR=%q\n' "$REPO_DIR"
    printf 'RESET_ARGS=('
    for arg in ${reset_args[@]+"${reset_args[@]}"}; do
      printf ' %q' "$arg"
    done
    printf ' )\n'
    cat <<'REMOTE_SCRIPT'
set -euo pipefail
cd "$REPO_DIR"
exec bash scripts/reset_demo_paper_ledgers.sh "${RESET_ARGS[@]}"
REMOTE_SCRIPT
  } | ssh -o BatchMode=yes -o ConnectTimeout=10 -- "$SSH_TARGET" bash -s
}

remote_python_module() {
  local module="$1"
  shift
  local -a module_args=("$@")
  local arg
  {
    printf 'REPO_DIR=%q\n' "$REPO_DIR"
    printf 'MODULE=%q\n' "$module"
    printf 'MODULE_ARGS=('
    for arg in ${module_args[@]+"${module_args[@]}"}; do
      printf ' %q' "$arg"
    done
    printf ' )\n'
    cat <<'REMOTE_SCRIPT'
set -euo pipefail
cd "$REPO_DIR"
exec .venv/bin/python -m "$MODULE" "${MODULE_ARGS[@]}"
REMOTE_SCRIPT
  } | ssh -o BatchMode=yes -o ConnectTimeout=10 -- "$SSH_TARGET" bash -s
}

command="${1:-help}"
if [[ "$#" -gt 0 ]]; then
  shift
fi

case "$command" in
  help|-h|--help)
    usage
    ;;
  status)
    exec "$ROOT_DIR/scripts/deploy_vps_live.sh" verify "$@"
    ;;
  equity)
    exec bash "$ROOT_DIR/scripts/equity_curves.sh" "$@"
    ;;
  research-refresh)
    exec bash "$ROOT_DIR/scripts/research_refresh.sh" "$@"
    ;;
  reset)
    remote_reset "$@"
    ;;
  venue-accounting)
    exec "$PYTHON_BIN" "$ROOT_DIR/scripts/reconcile_bybit_demo_accounting.py" "$@"
    ;;
  real-money)
    # The owner-facing arming surface. `preflight` reads only and never prints
    # a secret. `render-profile` without --execute prints the profile to
    # stdout; with --execute it writes exactly one non-secret artifact and
    # refuses any dial set that does not pass the load-time envelope proof.
    # Neither sets REAL_MONEY, writes a credential, or starts
    # a unit -- every one of those is the owner's own act.
    # No argument means preflight, and it has to be *passed*: leaving argv
    # empty ran the module with no subcommand and got an argparse usage error
    # instead of the read-only report the operator asked for.
    if [[ "$#" -eq 0 ]]; then
      set -- preflight
    fi
    case "${1:-}" in
      preflight|render-profile) ;;
      *) die_usage "real-money subcommand must be preflight or render-profile" ;;
    esac
    # LOCAL=1 runs it against this checkout instead of the VPS, so the dials
    # can be proved before anything is copied to the host.
    if [[ "${LOCAL:-0}" == "1" ]]; then
      exec "$PYTHON_BIN" -m liquidity_migration.real_money_arming "$@"
    fi
    remote_python_module liquidity_migration.real_money_arming "$@"
    ;;
  wedged-command)
    # B15b. `report` and `probe` read only. `resolve` writes one journal
    # transition and never resends an order; it refuses outright when the
    # venue still holds the order or cannot be read.
    if [[ "${1:-}" == "--execute" ]]; then
      shift
      [[ "${1:-}" == "resolve" ]] \
        || die_usage "wedged-command --execute is valid only before the resolve subcommand"
    elif [[ "${1:-}" == "resolve" ]]; then
      die_usage "wedged-command resolve writes a journal transition; prefix it with --execute"
    fi
    remote_python_module liquidity_migration.wedged_command_resolution "$@"
    ;;
  test)
    exec "$PYTHON_BIN" -m pytest "$@"
    ;;
  deploy)
    [[ "${1:-}" == "--execute" ]] \
      || die_usage "deploy is mutating; its first argument must be --execute"
    shift
    [[ "${1:-}" == "install" || "${1:-}" == "activate" || "${1:-}" == "rollout" ]] \
      || die_usage "deploy mode must be install, activate, or rollout"
    exec "$ROOT_DIR/scripts/deploy_vps_live.sh" "$@"
    ;;
  *)
    die_usage "unknown command '$command'"
    ;;
esac
