#!/usr/bin/env bash
# One thin operator-facing router for the surviving demo/paper and research operations.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SSH_TARGET="${SSH_TARGET:-root@116.202.15.128}"
REPO_DIR="${REPO_DIR:-/opt/liquidity-migration}"

if [[ -n "${PYTHON:-}" ]]; then
  PYTHON_BIN="$PYTHON"
elif [[ -x "$ROOT_DIR/.venv/bin/python" ]]; then
  PYTHON_BIN="$ROOT_DIR/.venv/bin/python"
elif [[ -x "$ROOT_DIR/.venv/Scripts/python.exe" ]]; then
  PYTHON_BIN="$ROOT_DIR/.venv/Scripts/python.exe"
else
  PYTHON_BIN="python3"
fi

# The canonical VPS scripts consume these environment variables.
export SSH_TARGET REPO_DIR

usage() {
  cat <<'EOF'
Usage: scripts/ops.sh <command> [arguments]

Safe operator commands:
  status [ARGS...]             read-only VPS verification
  equity [ARGS...]             standard descriptive equity curves
  research-refresh [ARGS...]   append-first data/features/backtest workflow
  reset [ARGS...]              remote ledger-reset preview (dry-run by default)
  clock-offset --execute [...] capture VPS-vs-Bybit public clock evidence
  operational-authority [ARGS...]
                               verify exact demo/paper operational authority
  operational-authority --execute issue [ARGS...]
                               issue narrow demo or demo+paper authority
  venue-accounting [ARGS...]   capture/reconcile read-only demo accounting evidence
  test [PYTEST_ARGS...]        run pytest
  deploy --execute MODE        run stopped install or authorized activation
  help                         show this help and do nothing else

Environment overrides:
  SSH_TARGET   VPS SSH destination (default: root@116.202.15.128)
  REPO_DIR     repository path on the VPS (default: /opt/liquidity-migration)
  PYTHON       Python executable/path for local tools and tests

Safety contract:
  * This interface never enables REAL_MONEY or mainnet trading.
  * reset is a remote dry-run unless --execute reaches the guarded reset script.
  * clock-offset requires --execute and runs on the VPS clock.
  * deploy requires --execute and MODE=install|activate.
  * Research runs remain research artifacts and are never auto-promoted.

Details: docs/operations.md
EOF
}

die_usage() {
  echo "ERROR: $*" >&2
  echo >&2
  usage >&2
  exit 2
}

remote_reset() {
  local -a reset_args=("$@")
  local arg has_execute=0 has_dry_run=0
  for arg in "${reset_args[@]:-}"; do
    if [[ "$arg" == "--execute" ]]; then
      has_execute=1
    elif [[ "$arg" == "--dry-run" ]]; then
      has_dry_run=1
    fi
  done

  # Make the safe default explicit at the remote boundary. The canonical reset
  # script independently defaults to dry-run and requires --execute as well.
  if (( has_execute == 0 && has_dry_run == 0 )); then
    reset_args=(--dry-run "${reset_args[@]}")
  fi

  # Serialize values as Bash literals, then reconstruct a remote array. This
  # preserves argument boundaries (including spaces/metacharacters) without
  # eval. The only parsed source is generated by Bash's own printf %q.
  {
    printf 'REPO_DIR=%q\n' "$REPO_DIR"
    printf 'RESET_ARGS=('
    for arg in "${reset_args[@]}"; do
      printf ' %q' "$arg"
    done
    printf ' )\n'
    cat <<'REMOTE_SCRIPT'
set -euo pipefail
cd "$REPO_DIR"
exec bash scripts/reset_demo_paper_ledgers.sh "${RESET_ARGS[@]}"
REMOTE_SCRIPT
  } | ssh -o BatchMode=yes -o ConnectTimeout=10 -- "$SSH_TARGET" bash -s
}

remote_python_script() {
  local script_path="$1"
  shift
  local -a script_args=("$@")
  local arg
  {
    printf 'REPO_DIR=%q\n' "$REPO_DIR"
    printf 'SCRIPT_PATH=%q\n' "$script_path"
    printf 'SCRIPT_ARGS=('
    for arg in "${script_args[@]}"; do
      printf ' %q' "$arg"
    done
    printf ' )\n'
    cat <<'REMOTE_SCRIPT'
set -euo pipefail
cd "$REPO_DIR"
exec .venv/bin/python "$SCRIPT_PATH" "${SCRIPT_ARGS[@]}"
REMOTE_SCRIPT
  } | ssh -o BatchMode=yes -o ConnectTimeout=10 -- "$SSH_TARGET" bash -s
}

remote_python_module() {
  local module="$1"
  shift
  local -a module_args=("$@")
  local arg
  {
    printf 'REPO_DIR=%q\n' "$REPO_DIR"
    printf 'MODULE=%q\n' "$module"
    printf 'MODULE_ARGS=('
    for arg in "${module_args[@]}"; do
      printf ' %q' "$arg"
    done
    printf ' )\n'
    cat <<'REMOTE_SCRIPT'
set -euo pipefail
cd "$REPO_DIR"
exec .venv/bin/python -m "$MODULE" "${MODULE_ARGS[@]}"
REMOTE_SCRIPT
  } | ssh -o BatchMode=yes -o ConnectTimeout=10 -- "$SSH_TARGET" bash -s
}

remote_operational_authority_issue() {
  local -a authority_args=("$@")
  local arg
  {
    printf 'REPO_DIR=%q\n' "$REPO_DIR"
    printf 'AUTHORITY_ARGS=('
    for arg in "${authority_args[@]}"; do
      printf ' %q' "$arg"
    done
    printf ' )\n'
    cat <<'REMOTE_SCRIPT'
set -euo pipefail
PATH=/usr/sbin:/usr/bin:/sbin:/bin
export PATH
umask 077

MAINTENANCE_LOCK=/run/liquidity-migration/maintenance.lock
LEGACY_DEPLOY_LOCK=/run/liquidity-migration/deploy.lock
LEGACY_RESET_LOCK=/run/lock/liquidity-migration-ledger-reset.lock
[[ -x /usr/bin/flock && ! -L /usr/bin/flock ]] \
  || { echo "operational authority requires trusted /usr/bin/flock" >&2; exit 1; }

# Acquire before opening the checkout or its Python environment. This prevents
# a concurrent install from changing the module while Python imports it and
# bridges deployed reset/deploy versions that still use either legacy leaf.
exec 9<"$MAINTENANCE_LOCK" \
  || { echo "cannot open canonical maintenance lock" >&2; exit 1; }
/usr/bin/flock -n 9 \
  || { echo "another maintenance operation is active" >&2; exit 1; }
exec 8<"$LEGACY_DEPLOY_LOCK" \
  || { echo "cannot open legacy deploy lock" >&2; exit 1; }
/usr/bin/flock -n 8 \
  || { echo "a legacy deploy operation is active" >&2; exit 1; }
exec 7<"$LEGACY_RESET_LOCK" \
  || { echo "cannot open legacy reset lock" >&2; exit 1; }
/usr/bin/flock -n 7 \
  || { echo "a legacy reset operation is active" >&2; exit 1; }

cd "$REPO_DIR"
PYTHON="$REPO_DIR/.venv/bin/python"
HELPER="$REPO_DIR/liquidity_migration/maintenance_lock.py"
[[ -x "$PYTHON" ]] \
  || { echo "deployed Python is unavailable" >&2; exit 1; }
[[ -f "$HELPER" && ! -L "$HELPER" ]] \
  || { echo "maintenance lock helper is unavailable or unsafe" >&2; exit 1; }

helper_output="$(/usr/bin/python3 "$HELPER" prepare-host)" \
  || { echo "cannot validate prepared maintenance locks" >&2; exit 1; }
IFS=$'\t' read -r \
  maintenance_device maintenance_inode deploy_device deploy_inode reset_device reset_inode \
  <<< "$helper_output"
for value in \
  "$maintenance_device" "$maintenance_inode" "$deploy_device" \
  "$deploy_inode" "$reset_device" "$reset_inode"; do
  [[ "$value" =~ ^[0-9]+$ ]] \
    || { echo "maintenance helper returned invalid identity metadata" >&2; exit 1; }
done
/usr/bin/python3 "$HELPER" acquire-inherited \
  --lock 9 "$MAINTENANCE_LOCK" "$maintenance_device" "$maintenance_inode" \
  --lock 8 "$LEGACY_DEPLOY_LOCK" "$deploy_device" "$deploy_inode" \
  --lock 7 "$LEGACY_RESET_LOCK" "$reset_device" "$reset_inode" \
  || { echo "maintenance lock identity changed" >&2; exit 1; }

export LIQUIDITY_MIGRATION_MAINTENANCE_LOCK_FDS=9,8,7
exec "$PYTHON" -m liquidity_migration.operational_runtime_authority "${AUTHORITY_ARGS[@]}"
REMOTE_SCRIPT
  } | ssh -o BatchMode=yes -o ConnectTimeout=10 -- "$SSH_TARGET" bash -s
}

command="${1:-help}"
if [[ "$#" -gt 0 ]]; then
  shift
fi

case "$command" in
  help|-h|--help)
    usage
    ;;
  status)
    exec "$ROOT_DIR/scripts/deploy_vps_live.sh" verify "$@"
    ;;
  equity)
    exec bash "$ROOT_DIR/scripts/equity_curves.sh" "$@"
    ;;
  research-refresh)
    exec bash "$ROOT_DIR/scripts/research_refresh.sh" "$@"
    ;;
  reset)
    remote_reset "$@"
    ;;
  clock-offset)
    [[ "${1:-}" == "--execute" ]] \
      || die_usage "clock-offset writes a VPS-bound receipt; its first argument must be --execute"
    shift
    remote_python_script scripts/capture_bybit_clock_offset.py "$@"
    ;;
  operational-authority)
    if [[ "${1:-}" == "--execute" ]]; then
      shift
      [[ "${1:-}" == "issue" ]] \
        || die_usage "operational-authority --execute is valid only before the issue subcommand"
      remote_operational_authority_issue "$@"
    elif [[ "${1:-}" == "issue" ]]; then
      die_usage "operational-authority issue mutates the VPS; prefix it with --execute"
    else
      if [[ "$#" -eq 0 ]]; then
        set -- verify --repo-root "$REPO_DIR"
      fi
      remote_python_module liquidity_migration.operational_runtime_authority "$@"
    fi
    ;;
  venue-accounting)
    exec "$PYTHON_BIN" "$ROOT_DIR/scripts/reconcile_bybit_demo_accounting.py" "$@"
    ;;
  test)
    exec "$PYTHON_BIN" -m pytest "$@"
    ;;
  deploy)
    [[ "${1:-}" == "--execute" ]] \
      || die_usage "deploy is mutating; its first argument must be --execute"
    shift
    [[ "${1:-}" == "install" || "${1:-}" == "activate" ]] \
      || die_usage "deploy mode must be install or activate"
    exec "$ROOT_DIR/scripts/deploy_vps_live.sh" "$@"
    ;;
  *)
    die_usage "unknown command '$command'"
    ;;
esac
