#!/usr/bin/env bash
# One thin operator-facing router for the surviving demo and research operations.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SSH_TARGET="${SSH_TARGET:-root@208.84.103.4}"
REPO_DIR="${REPO_DIR:-/opt/liquidity-migration}"
LM_FLEET_MANIFEST="$ROOT_DIR/deploy/fleet_manifest.tsv"
. "$ROOT_DIR/deploy/lib_sleeves.sh"

if [[ -n "${PYTHON:-}" ]]; then
  PYTHON_BIN="$PYTHON"
elif [[ -x "$ROOT_DIR/.venv/bin/python" ]]; then
  PYTHON_BIN="$ROOT_DIR/.venv/bin/python"
elif [[ -x "$ROOT_DIR/.venv/Scripts/python.exe" ]]; then
  PYTHON_BIN="$ROOT_DIR/.venv/Scripts/python.exe"
else
  PYTHON_BIN="python3"
fi

# The canonical VPS scripts consume these environment variables.
export SSH_TARGET REPO_DIR

usage() {
  cat <<'EOF'
Usage: scripts/ops.sh <command> [arguments]

Operator commands:
  status                       read-only VPS verification
  units                        list the fleet's units and timers
  logs UNIT [LINES]            one unit's journal (default 100 lines)
  restart UNIT...              restart units
  stop UNIT...                 stop units
  start UNIT...                start units
  equity [ARGS...]             standard descriptive equity curves (research)
  execution-study [--json]     read the latest paired execution cost report
  curve [REALM] [SAMPLES]      the live account's recorded equity curve, read
                               on the host (default: mainnet, 240 minutes;
                               REALM is demo, mainnet or mexc)
  flatten --environment demo|mainnet|mexc [--reason TEXT] [--execute]
                               ask each native directional reducer to close its
                               attributed exposure through durable Rust control
                               commands. Reports without --execute; the signal
                               worker stays live while exits complete
  attest-flat --environment demo|mainnet|mexc
                               run the installed Rust adapter's credential-wide
                               two-scan flatness proof (read-only)
  verify-account-identity --environment demo|mainnet|mexc
                               authenticate the realm's read-only probe and
                               print the account id the engine binds
  canary-order --environment demo|mexc --symbol SYMBOL
               --expected-user-id ID [--execute]
                               one bounded live order lifecycle on the realm's
                               account: rest one minimum post-only order away
                               from the touch, cancel it, prove the account
                               clean twice. Without --execute nothing is sent
  research-refresh [ARGS...]   append-first data/features/backtest workflow
  real-money preflight         report every remaining arming step for the
                               funded Bybit account (read-only)
  real-money preflight-mexc    the same for the MEXC account (read-only)
  real-money render-profile [--execute --output PATH]
                               render the operational profile from the
                               RM_* dials in the funded credential file
  deploy [MODE]                MODE is deploy (default)|rollback|verify|
                               stop-mainnet|disarm-mainnet|stop-mexc|
                               disarm-mexc; rollback deploys the last commit
                               whose deploy finished
  help                         show this help and do nothing else

A UNIT that does not already start with `liquidity-migration-` gets the prefix:
`logs signal-worker-demo.service` reads
`liquidity-migration-signal-worker-demo.service`.

Environment overrides:
  SSH_TARGET   VPS SSH destination (default: root@208.84.103.4)
  REPO_DIR     repository path on the VPS (default: /opt/liquidity-migration)
  PYTHON       Python executable/path for local tools and tests

Mutating verbs run against the live host; see docs/operations.md.
EOF
}

die_usage() {
  echo "ERROR: $*" >&2
  echo >&2
  usage >&2
  exit 2
}

# One remote entry point. Values are serialized as Bash literals and
# reconstructed as a remote array, which preserves argument boundaries
# (including spaces and metacharacters) without eval: the only parsed source is
# generated by Bash's own printf %q.
remote_exec() {
  local script="$1"
  shift
  local -a remote_args=("$@")
  local arg
  {
    printf 'REPO_DIR=%q\n' "$REPO_DIR"
    printf 'REMOTE_ARGS=('
    for arg in ${remote_args[@]+"${remote_args[@]}"}; do
      printf ' %q' "$arg"
    done
    printf ' )\n'
    printf 'set -euo pipefail\n'
    printf '%s\n' "$script"
  } | ssh -o BatchMode=yes -o ConnectTimeout=10 -- "$SSH_TARGET" bash -s
}

qualify_unit() {
  case "$1" in
    liquidity-migration-*) printf '%s' "$1" ;;
    *) printf 'liquidity-migration-%s' "$1" ;;
  esac
}

qualified_units() {
  local unit
  QUALIFIED_UNITS=()
  for unit in "$@"; do
    QUALIFIED_UNITS+=("$(qualify_unit "$unit")")
  done
}

remote_python_module() {
  local module="$1"
  shift
  remote_exec 'cd "$REPO_DIR"
exec .venv/bin/python -m "${REMOTE_ARGS[@]}"' "$module" "$@"
}

# remote_engine_control REALM MODE [ARGS...]
#   attest-flat and verify-account-identity are read-only and run with the
#   arming switch removed. canary-order keeps REAL_MONEY: a live-canary realm's
#   gateway refuses to build without it, and the command places one order.
remote_engine_control() {
  local realm="$1"
  shift
  remote_exec '
realm="${REMOTE_ARGS[0]}"
mode="${REMOTE_ARGS[1]}"
engine_args=("${REMOTE_ARGS[@]:2}")
engine_binary=/opt/liquidity-migration-engine/bin/engine

case "$realm" in
  demo)
    env_file=/etc/liquidity-migration/engine.env
    credential_file=/etc/liquidity-migration/bybit-demo.env
    inventory_credential_set=demo
    runtime_user=liquidity-engine-demo
    state_dir=/var/lib/liquidity-migration-engine
    unset_environment="BYBIT_REAL_API_KEY BYBIT_REAL_API_SECRET BYBIT_REAL_API_KEY_IP BYBIT_REAL_API_KEY_BACKUP_IP BYBIT_ATTEST_API_KEY BYBIT_ATTEST_API_SECRET BYBIT_ATTEST_API_KEY_IP BYBIT_ENGINE_EXCLUSIVE_ACCOUNT_USER_ID REAL_MONEY TELEGRAM_BOT_TOKEN TELEGRAM_CHAT_ID TELEGRAM_ALERT_CHAT_ID"
    ;;
  mainnet)
    env_file=/etc/liquidity-migration/engine-mainnet.env
    credential_file=/etc/liquidity-migration/bybit-mainnet.env
    inventory_credential_set=execution
    if [ -e /etc/liquidity-migration/bybit-mainnet-attestor.env ]; then
      credential_file=/etc/liquidity-migration/bybit-mainnet-attestor.env
      inventory_credential_set=attestor
    fi
    runtime_user=liquidity-engine-mainnet
    state_dir=/var/lib/liquidity-migration-engine-mainnet
    if [ "$inventory_credential_set" = attestor ]; then
      unset_environment="BYBIT_REAL_API_KEY BYBIT_REAL_API_SECRET BYBIT_REAL_API_KEY_IP BYBIT_REAL_API_KEY_BACKUP_IP BYBIT_DEMO_API_KEY BYBIT_DEMO_API_SECRET MEXC_REAL_API_KEY MEXC_REAL_API_SECRET REAL_MONEY TELEGRAM_BOT_TOKEN TELEGRAM_CHAT_ID TELEGRAM_ALERT_CHAT_ID"
    else
      unset_environment="BYBIT_ATTEST_API_KEY BYBIT_ATTEST_API_SECRET BYBIT_ATTEST_API_KEY_IP BYBIT_DEMO_API_KEY BYBIT_DEMO_API_SECRET MEXC_REAL_API_KEY MEXC_REAL_API_SECRET REAL_MONEY TELEGRAM_BOT_TOKEN TELEGRAM_CHAT_ID TELEGRAM_ALERT_CHAT_ID"
    fi
    ;;
  mexc)
    env_file=/etc/liquidity-migration/engine-mexc.env
    credential_file=/etc/liquidity-migration/mexc-mainnet.env
    # MEXC has no separate read-only attestor key; this is the execution pair,
    # and the Rust inventory type it reaches exposes no mutation method.
    inventory_credential_set=execution
    runtime_user=liquidity-engine-mexc
    state_dir=/var/lib/liquidity-migration-engine-mexc
    unset_environment="BYBIT_DEMO_API_KEY BYBIT_DEMO_API_SECRET BYBIT_REAL_API_KEY BYBIT_REAL_API_SECRET BYBIT_REAL_API_KEY_IP BYBIT_REAL_API_KEY_BACKUP_IP BYBIT_ATTEST_API_KEY BYBIT_ATTEST_API_SECRET BYBIT_ATTEST_API_KEY_IP BYBIT_ENGINE_EXCLUSIVE_ACCOUNT_USER_ID REAL_MONEY TELEGRAM_BOT_TOKEN TELEGRAM_CHAT_ID TELEGRAM_ALERT_CHAT_ID"
    ;;
  *) echo "invalid engine-control realm: $realm" >&2; exit 2 ;;
esac

case "$mode" in
  attest-flat|verify-account-identity) ;;
  canary-order)
    unset_environment="$(printf "%s\n" $unset_environment | grep -vx REAL_MONEY | tr "\n" " ")"
    ;;
  *) echo "invalid engine-control mode: $mode" >&2; exit 2 ;;
esac

[ -x "$engine_binary" ] \
  || { echo "installed Rust engine is missing: $engine_binary" >&2; exit 3; }
for path in "$env_file" "$credential_file"; do
  [ -f "$path" ] \
    || { echo "engine-control input is missing: $path" >&2; exit 3; }
done

# systemd parses the private EnvironmentFiles, then drops privileges. The
# command receives one explicitly selected credential file. For the read-only
# modes the Rust inventory type exposes no mutation method even on the
# execution file. Secrets never enter this router or its argv.
exec systemd-run --quiet --wait --pipe --collect --service-type=exec \
    --unit="liquidity-migration-${mode}-${realm}-$$" \
    --property="User=$runtime_user" \
    --property="Group=liquidity-migration" \
    --property="WorkingDirectory=$state_dir" \
    --property="EnvironmentFile=$env_file" \
    --property="EnvironmentFile=$credential_file" \
    --property="Environment=BYBIT_INVENTORY_CREDENTIAL_SET=$inventory_credential_set" \
    --property="UnsetEnvironment=$unset_environment" \
    --property=NoNewPrivileges=true \
    --property=PrivateTmp=true \
    --property=ProtectSystem=strict \
    --property=ProtectHome=true \
    --property=UMask=0027 \
    "$engine_binary" "$mode" ${engine_args[@]+"${engine_args[@]}"}
' "$realm" "$@"
}

command="${1:-help}"
if [[ "$#" -gt 0 ]]; then
  shift
fi

case "$command" in
  help|-h|--help)
    usage
    ;;
  status)
    exec "$ROOT_DIR/scripts/deploy_vps_live.sh" verify
    ;;
  units)
    lm_validate_fleet_manifest || die_usage "fleet manifest is invalid"
    FLEET_UNITS=()
    while IFS= read -r unit; do
      FLEET_UNITS+=("$unit")
    done < <(lm_expected_systemd_units)
    [[ "${#FLEET_UNITS[@]}" -gt 0 ]] || die_usage "fleet manifest has no current units"
    remote_exec 'systemctl list-units "${REMOTE_ARGS[@]}" --all --no-legend --no-pager --plain
systemctl list-timers "${REMOTE_ARGS[@]}" --all --no-pager' "${FLEET_UNITS[@]}"
    ;;
  logs)
    [[ "$#" -ge 1 ]] || die_usage "logs requires a unit name"
    remote_exec 'exec journalctl -u "${REMOTE_ARGS[0]}" -n "${REMOTE_ARGS[1]}" --no-pager -o short-iso' \
      "$(qualify_unit "$1")" "${2:-100}"
    ;;
  restart|stop|start)
    [[ "$#" -ge 1 ]] || die_usage "$command requires at least one unit name"
    qualified_units "$@"
    for unit in "${QUALIFIED_UNITS[@]}"; do
      [[ "$unit" =~ ^liquidity-migration-[A-Za-z0-9_.@:-]+$ ]] \
        || die_usage "invalid systemd unit name '$unit'"
    done
    remote_exec "exec systemctl $command \"\${REMOTE_ARGS[@]}\"" "${QUALIFIED_UNITS[@]}"
    ;;
  equity)
    exec bash "$ROOT_DIR/scripts/research/equity_curves.sh" "$@"
    ;;
  curve)
    # The live account's own recorded curve, read on the host from the file
    # the minute recorder appends to. Read-only, and it says nothing about
    # research backtests -- that is `equity` above.
    curve_realm="${1:-mainnet}"
    case "$curve_realm" in
      demo|mainnet|mexc) ;;
      *) die_usage "curve realm must be demo, mainnet or mexc" ;;
    esac
    curve_samples="${2:-240}"
    [[ "$curve_samples" =~ ^[1-9][0-9]*$ ]] || die_usage "curve samples must be a positive integer"
    remote_exec 'exec /opt/liquidity-migration-engine/bin/engine-tools record-equity \
      --show "${REMOTE_ARGS[0]}" --samples "${REMOTE_ARGS[1]}"' "$curve_realm" "$curve_samples"
    ;;
  execution-study)
    [[ "$#" -le 1 ]] || die_usage "execution-study accepts only --json"
    study_file=latest.txt
    if [[ "$#" -eq 1 ]]; then
      [[ "$1" == --json ]] || die_usage "execution-study accepts only --json"
      study_file=latest.json
    fi
    remote_exec 'cat -- "/var/lib/liquidity-migration/execution-study/${REMOTE_ARGS[0]}"' "$study_file"
    ;;
  research-refresh)
    exec bash "$ROOT_DIR/scripts/research/research_refresh.sh" "$@"
    ;;
  real-money)
    # The arming surface. `preflight` reads only and never prints
    # a secret. `render-profile` without --execute prints the profile to
    # stdout; with --execute it writes exactly one non-secret artifact and
    # refuses any dial set that does not pass the load-time envelope proof.
    # Neither command sets REAL_MONEY, writes a credential, or starts a unit.
    # No argument means preflight, and it must be passed: an empty argv reaches
    # the module with no subcommand and argparse answers with a usage error.
    if [[ "$#" -eq 0 ]]; then
      set -- preflight
    fi
    case "${1:-}" in
      preflight|preflight-mexc|render-profile) ;;
      *) die_usage "real-money subcommand must be preflight, preflight-mexc or render-profile" ;;
    esac
    # LOCAL=1 runs it against this checkout instead of the VPS, so the dials
    # can be proved before anything is copied to the host.
    if [[ "${LOCAL:-0}" == "1" ]]; then
      exec "$PYTHON_BIN" -m liquidity_migration.policy.real_money_arming "$@"
    fi
    remote_python_module liquidity_migration.policy.real_money_arming "$@"
    ;;
  flatten)
    # On the engine's own path: durably disable entries, submit one replayable
    # flatten request per native directional reducer, then wait for the engine
    # heartbeat to show no attributed position or opening work.
    #
    # Dry run unless --execute, and made explicit here as well as in the script
    # so neither side alone can turn a report into a close.
    flatten_args=("$@")
    has_execute=0
    for arg in ${flatten_args[@]+"${flatten_args[@]}"}; do
      [ "$arg" = "--execute" ] && has_execute=1
    done
    if (( has_execute == 0 )); then
      flatten_args=(--dry-run ${flatten_args[@]+"${flatten_args[@]}"})
    fi
    # The script body must consume REMOTE_ARGS itself: remote_exec serializes
    # the arguments into a remote shell array, and a bare path here runs the
    # script with no argv at all — which flatten_account.sh refuses.
    remote_exec 'exec bash "$REPO_DIR/scripts/vps/flatten_account.sh" "${REMOTE_ARGS[@]}"' \
      ${flatten_args[@]+"${flatten_args[@]}"}
    ;;
  attest-flat)
    [[ "$#" -eq 2 && "$1" == "--environment" ]] \
      || die_usage "attest-flat requires --environment demo|mainnet|mexc"
    case "$2" in
      demo|mainnet|mexc) ;;
      *) die_usage "attest-flat environment must be demo, mainnet or mexc" ;;
    esac
    remote_engine_control "$2" attest-flat
    ;;
  verify-account-identity)
    [[ "$#" -eq 2 && "$1" == "--environment" ]] \
      || die_usage "verify-account-identity requires --environment demo|mainnet|mexc"
    case "$2" in
      demo|mainnet|mexc) ;;
      *) die_usage "verify-account-identity environment must be demo, mainnet or mexc" ;;
    esac
    remote_engine_control "$2" verify-account-identity
    ;;
  canary-order)
    canary_environment="" canary_symbol="" canary_user_id="" canary_execute=""
    while [[ "$#" -gt 0 ]]; do
      case "$1" in
        --environment) canary_environment="${2:-}"; shift 2 ;;
        --symbol) canary_symbol="${2:-}"; shift 2 ;;
        --expected-user-id) canary_user_id="${2:-}"; shift 2 ;;
        --execute) canary_execute=1; shift ;;
        *) die_usage "canary-order does not take '$1'" ;;
      esac
    done
    # bybit_mainnet is live-proven and never the canary's account; the engine
    # refuses it too, but a typo should stop here, before the host.
    case "$canary_environment" in
      demo|mexc) ;;
      *) die_usage "canary-order requires --environment demo|mexc" ;;
    esac
    [[ -n "$canary_symbol" && -n "$canary_user_id" ]] \
      || die_usage "canary-order requires --symbol SYMBOL and --expected-user-id ID"
    remote_engine_control "$canary_environment" canary-order \
      --symbol "$canary_symbol" --expected-user-id "$canary_user_id" \
      ${canary_execute:+--execute}
    ;;
  deploy)
    # A leading --execute is accepted and discarded, for callers that still pass it.
    if [[ "${1:-}" == "--execute" ]]; then
      shift
    fi
    case "${1:-deploy}" in
      deploy|rollback|verify|stop-mainnet|disarm-mainnet|stop-mexc|disarm-mexc) ;;
      *) die_usage "deploy mode must be deploy, rollback, verify, stop-mainnet, disarm-mainnet, stop-mexc, or disarm-mexc" ;;
    esac
    exec "$ROOT_DIR/scripts/deploy_vps_live.sh" "${1:-deploy}"
    ;;
  *)
    die_usage "unknown command '$command'"
    ;;
esac
